run:
  timeout: 5m
  skip-dirs-use-default: true
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: '1.20'

output:
  sort-results: true

linters:
  disable-all: true
  enable:
    - gci
    - revive

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/javorszky/go-responsewriter-lint)
      - blank
      - dot
    custom-order: true
  revive:
    max-open-files: 2048
    ignore-generated-header: true
    enable-all-rules: false
    confidence: 0.1
    rules:
      - name: import-shadowing
        severity: warning
        disabled: false
      - name: duplicated-imports
        severity: warning
        disabled: false
