name: ci

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: write
  packages: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-cache: true
          args: -v

  test:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: false
      - run: go mod download
      - run: make test
